# This is a basic workflow to help you get started with Actions

name: Primeiro CI


on:


 push:
   branches: [ "main" ]
 pull_request:
   branches: [ "main" ]


jobs:
 Compilar:
 #Cria máquina virtual para usar no pipeline
   runs-on: ubuntu-latest


   steps:
     - name: Fazer o git clone
       uses: actions/checkout@v4


     - name: Executando primeiro comando
       run: echo "Hello, world!"
    
     - name: Executando dois ou mais comandos
       run: |
          ls -l
          echo Fim do PROCESSO
